<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Velto</RootNamespace>
    <AssemblyName>Velto</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\Resources\Velto.ico</ApplicationIcon>
    <Version>0.1.0</Version>
    <Product>Velto</Product>
    <Company>face</Company>
    <Copyright>2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Velto.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\Resources\Velto.ico">
      <Link>Resources\Velto.ico</Link>
    </Resource>
    <Resource Include="..\Resources\Velto.png">
      <Link>Resources\Velto.png</Link>
    </Resource>
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>embedded</DebugType>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

</Project>
